#@ load("@ytt:data", "data")
---
#! Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-pushgateway
  labels:
    component: pushgateway
    metrics: prometheus
  namespace: #@ data.values.system_namespace
---
#! Source: prometheus/templates/services/pushgateway.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: pushgateway
  labels:
    component: pushgateway
    metrics: prometheus
  name: prometheus-pushgateway
  namespace: #@ data.values.system_namespace
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    component: pushgateway
    metrics: prometheus
  type: ClusterIP
---
#! Source: prometheus/templates/rbac/pushgateway-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    component: pushgateway
    metrics: prometheus
  name: prometheus-pushgateway
rules:
  []
---
#! Source: prometheus/templates/rbac/pushgateway-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    component: pushgateway
    metrics: prometheus
  name: prometheus-pushgateway
subjects:
  - kind: ServiceAccount
    name: prometheus-pushgateway
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-pushgateway
---
#! Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  labels:
    component: pushgateway
    metrics: prometheus
  namespace: #@ data.values.system_namespace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: pushgateway
      metrics: prometheus
  template:
    metadata:
      labels:
        component: pushgateway
        metrics: prometheus
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "9091"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "cloudfoundry/prometheus-pushgateway:v1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
