#@ load("@ytt:data", "data")
---
#! Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-pushgateway
  labels:
    component: pushgateway
    metrics: prometheus
  namespace: #@ data.values.system_namespace
---
#! Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  annotations:
    {}
  labels:
    component: pushgateway
    metrics: prometheus
  namespace: #@ data.values.system_namespace
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    component: pushgateway
    metrics: prometheus
---
#! Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  labels:
    component: pushgateway
    metrics: prometheus
  namespace: #@ data.values.system_namespace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: pushgateway
      metrics: prometheus
  template:
    metadata:
      labels:
        component: pushgateway
        metrics: prometheus
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "9091"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "oratos/prometheus-pushgateway:v1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
